import initTranslations from '@/app/i18n';
import i18nConfig from '@/i18nConfig';
import TranslationsProvider from '@/components/TranslationProvider';
import { getUpcomingEventData } from '@/cms/event';
import type { Metadata } from 'next';
import PageContentBox from '@/components/layout/PageContentBox';
import Script from "next/script";
import {getDomain} from "@/cms/utils";

const i18nNamespaces = ['common'];

export const metadata: Metadata = {
  title: 'TICKETS Create Next App',
  description: 'Generated by create next app',
};

export const revalidate = 120;

export default async function Tickets({
  params: { locale },
}: {
  params: { locale: string };
}) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  const upcomingEventData = await getUpcomingEventData(locale);
  //console.log(JSON.stringify(upcomingEventData, null, 2));

  return (
    <TranslationsProvider
      locale={locale}
      namespaces={i18nNamespaces}
      resources={resources}
    >
      <main>
        <PageContentBox>
          {upcomingEventData?.ticket_shop_url ? (
            <div>
              <Script
                src={`${getDomain(upcomingEventData?.ticket_shop_url)}widget/v1.de-informal.js`}
                strategy="afterInteractive"
              />
              <link
                rel='stylesheet'
                type='text/css'
                href={`${upcomingEventData?.ticket_shop_url}widget/v1.css`}
              />
              <pretix-widget
                event={upcomingEventData?.ticket_shop_url}
                skip-ssl-check
              ></pretix-widget>
              <noscript>
                <div className='pretix-widget'>
                  <div className='pretix-widget-info-message'>
                    JavaScript ist in Ihrem Browser deaktiviert. Um unseren
                    Ticket-Shop ohne JavaScript aufzurufen, klicken Sie bitte{' '}
                    <a
                      target='_blank'
                      rel='noopener'
                      href={upcomingEventData?.ticket_shop_url}
                    >
                      hier
                    </a>
                    .
                  </div>
                </div>
              </noscript>
            </div>
          ) : null}
        </PageContentBox>
      </main>
    </TranslationsProvider>
  );
}

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}
