import initTranslations from '@/app/i18n';
import i18nConfig from '@/i18nConfig';
import TranslationsProvider from '@/components/TranslationProvider';
import { getUpcomingEventData } from '@/cms/event';
import type { Metadata } from 'next';
import { formatDateRange, getImageSrc } from '@/cms/utils';

const i18nNamespaces = ['common'];

export const metadata: Metadata = {
  title: 'HOME Create Next App',
  description: 'Generated by create next app',
};

export default async function Home({
  params: { locale },
}: {
  params: { locale: string };
}) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  const upcomingEventData = await getUpcomingEventData(locale);
  //console.log(JSON.stringify(upcomingEventData, null, 2));

  return (
    <TranslationsProvider
      locale={locale}
      namespaces={i18nNamespaces}
      resources={resources}
    >
      <main className=''>
        <div className='flex flex-col items-center'>
          <img
            src={getImageSrc(upcomingEventData?.image)}
            alt={upcomingEventData?.title}
            className='max-h-[250px] max-w-[60%] object-contain'
          />
          <div className='font-light tracking-[0.05em] lg:text-[42px]/[41px]'>
            {formatDateRange(
              new Date(upcomingEventData?.date_from),
              new Date(upcomingEventData?.date_to)
            )}
            {' @ '}
            {upcomingEventData?.event_location}
          </div>
        </div>
      </main>
    </TranslationsProvider>
  );
}

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}
