import initTranslations from '@/app/i18n';
import i18nConfig from '@/i18nConfig';
import TranslationsProvider from '@/components/TranslationProvider';
import { getUpcomingEventData } from '@/cms/event';
import type { Metadata } from 'next';
import { formatDateRange, getImageSrc } from '@/cms/utils';
import { Fragment } from 'react';
import PageContentBox from '@/components/layout/PageContentBox';
import StrapiRichtext from '@/components/layout/StrapiRichtext';

const i18nNamespaces = ['common'];

export const metadata: Metadata = {
  title: 'HOME Create Next App',
  description: 'Generated by create next app',
};

export const revalidate = 120;

export default async function Home({
  params: { locale },
}: {
  params: { locale: string };
}) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  const upcomingEventData = await getUpcomingEventData(locale);
  //console.log(JSON.stringify(upcomingEventData, null, 2));

  return (
    <TranslationsProvider
      locale={locale}
      namespaces={i18nNamespaces}
      resources={resources}
    >
      <main className=''>
        <div className='flex flex-col items-center'>
          <img
            src={getImageSrc(upcomingEventData?.image)}
            alt={upcomingEventData?.title}
            className='max-h-[250px] max-w-[60%] object-contain'
          />
          <div className='text-center font-light tracking-[0.05em] md:text-[24px]/[23px] lg:text-[42px]/[41px]'>
            {formatDateRange(
              new Date(upcomingEventData?.date_from),
              new Date(upcomingEventData?.date_to)
            )}
            {' @'}
            <Fragment>&nbsp;</Fragment>
            {upcomingEventData?.event_location}
          </div>
        </div>
        <PageContentBox className='mt-12 lg:mt-24'>
          <h2 className="relative text-2xl font-black italic tracking-[0.019em] [text-align-last:right] before:absolute before:-left-3 before:top-0 before:content-['\201E'] after:absolute after:-right-3 after:bottom-0 after:content-['\201C'] lg:text-[89px]/[86px] lg:before:-left-10 lg:after:-right-10">
            {upcomingEventData?.claim}
          </h2>
          <div className='mt-6 tracking-[0.019em] lg:mt-10 lg:text-[18px]/[25px]'>
            <StrapiRichtext content={upcomingEventData?.info} />
          </div>
        </PageContentBox>
      </main>
    </TranslationsProvider>
  );
}

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}
