name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # Passe es ggf. an deinen Haupt-Branch an

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and push the Docker image to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          NEXT_CMS_API: ${{ vars.NEXT_CMS_API }}
          NEXT_PUBLIC_CMS_UPLOADS: ${{ vars.NEXT_PUBLIC_CMS_UPLOADS }}
          NEXT_CMS_TOKEN: ${{ secrets.NEXT_CMS_TOKEN }}
        with:
          context: .
          push: true
          tags: ghcr.io/kulturevolution/entropiefestival-homepage/entropiefestival-homepage:latest, ghcr.io/kulturevolution/entropiefestival-homepage/entropiefestival-homepage:${{ github.sha }}
          # Du kannst zusätzliche Tags hinzufügen, wie z.B. den Commit SHA
          # tags: ghcr.io/your-github-username/your-image-name:latest, ghcr.io/your-github-username/your-image-name:${{ github.sha }}
